version: '3.8'

services:
  multi-ad-scraper:
    build: .
    container_name: multi_ad_scraper
    ports:
      - "5000:5000"
    volumes:
      - ./ads_output:/app/ads_output
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    mem_limit: 2g
    cpus: 1.0

volumes:
  ads_output:
  logs: